# docker-compose.yml
version: '2.4'  # Use version 2.x for this syntax

services:
  meta-expert:
    build: .
    ports:
      - "8105:8105"
    environment:
      - PYTHONUNBUFFERED=1  # Ensure Python output is not buffered
      - LLM_SHERPA_SERVER=http://nlm-ingestor:5001/api/parseDocument?renderFormat=all&useNewIndentParser=yes&applyOcr=no&timeout=15
    env_file:
      - .env
    depends_on:
      - nlm-ingestor
    volumes:
      - ./fastembed_cache:/app/fastembed_cache
      - ./reranker_cache:/app/reranker_cache
    mem_limit: 7.5g
    cpus: 5.0

  nlm-ingestor:
    image: ghcr.io/nlmatics/nlm-ingestor:latest
    ports:
      - "5001:5001"
